spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-user}
    password: ${db-pwd}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql:
  jackson:
    property-naming-strategy: SNAKE_CASE
    
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace